spring:
  datasource:
    username: ""
    password: ""
    url: "jdbc:h2:./app/taskManager"
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
